
"""desafio_ac1_master_sdwan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l91aPwOnqacXGkgWuzGVOoWneLxZqaf1
================================================================================
RELATÓRIO TÉCNICO - MOTOR DE DECISÃO SD-WAN ZERO-TRUST
================================================================================

1. TOPOLOGIA E CONTEXTO:
- A rede está configurada com 12 roteadores, começando no Nó 0 e terminando no Nó 11.
- Os nós 4 e 8 foram propositalmente marcados com um Índice de Segurança inferior a 50 (40 e 30, respectivamente), para simular ambientes não confiáveis ou comprometidos.

2. ANÁLISE DE ROTAS:
- A rota mais curta e rápida fisicamente gerada na rede é [0 -> 1 -> 4 -> 11], com latência muito baixa de 25ms. No entanto, o tráfego passaria pelo Nó 4, que tem sua reputação de segurança comprometida.
- A presença do Nó 4 ativa a política Zero-Trust, adicionando a constante de penalização P_Seguranca (5000) na função de Fitness, que funciona aqui como uma função de Custo a ser minimizada.

3. ROTA SELECIONADA E JUSTIFICATIVA DO DESVIO:
- O algoritmo estocástico ignorou as rotas vulneráveis e escolheu o melhor desvio: [0 -> 3 -> 6 -> 10 -> 11].
- Justificativa: Ao escolher esta rota, o motor de decisão SD-WAN aceita um aumento na latência total (de 25ms para 43ms) para garantir que todos os nós da trajetória tenham uma reputação igual ou superior a 50. A aplicação rigorosa de P_Seguranca (5000) torna inviáveis as rotas de risco, priorizando a segurança e a integridade dos pacotes em detrimento da velocidade máxima.

================================================================================
"""

import numpy as np
import random


np.random.seed(2026)
random.seed(2026)


W1_LATENCIA = 1.0     
W2_PERDA = 10.0       
P_SEGURANCA = 5000    


reputacao_seguranca = {
    0: 100, 1: 90, 2: 85, 3: 95,
    4: 40,  
    5: 90, 6: 80, 7: 95,
    8: 30,   
    9: 85, 10: 90, 11: 100
}


grafo = {
    0: {1: {'lat': 10, 'loss': 0.1}, 2: {'lat': 12, 'loss': 0.2}, 3: {'lat': 15, 'loss': 0.1}},
    1: {4: {'lat': 5,  'loss': 0.1}, 5: {'lat': 15, 'loss': 0.3}},
    2: {5: {'lat': 10, 'loss': 0.2}, 6: {'lat': 12, 'loss': 0.1}},
    3: {6: {'lat': 10, 'loss': 0.1}, 7: {'lat': 8,  'loss': 0.1}},
    4: {8: {'lat': 10, 'loss': 0.2}, 11: {'lat': 10, 'loss': 0.1}},
    5: {8: {'lat': 8,  'loss': 0.1}, 9: {'lat': 12, 'loss': 0.2}},
    6: {9: {'lat': 10, 'loss': 0.1}, 10: {'lat': 10, 'loss': 0.1}},
    7: {10: {'lat': 12, 'loss': 0.2}},
    8: {11: {'lat': 5,  'loss': 0.1}},
    9: {11: {'lat': 10, 'loss': 0.1}},
    10: {11: {'lat': 8,  'loss': 0.1}},
    11: {} 
}

def gerar_rota_aleatoria(origem, destino):
    """Gera uma rota válida caminhando aleatoriamente pelas adjacências."""
    rota = [origem]
    atual = origem
    while atual != destino:
        vizinhos = list(grafo[atual].keys())
      
        proximo = random.choice(vizinhos)
        rota.append(proximo)
        atual = proximo
    return rota

def calcular_fitness_custo(rota):
    """
    Função Objetivo: Fitness(X) = w1*Latencia + w2*PerdaPacotes + P_Seguranca
    Como queremos a 'melhor' rota, tratamos o Fitness como um CUSTO a ser MINIMIZADO.
    """
    latencia_total = 0.0
    perda_total = 0.0
    penalidade = 0


    for i in range(len(rota) - 1):
        u = rota[i]
        v = rota[i+1]
        latencia_total += grafo[u][v]['lat']
        perda_total += grafo[u][v]['loss']
    for no in rota:
        if reputacao_seguranca[no] < 50:
            penalidade = P_SEGURANCA
            break 

    fitness_custo = (W1_LATENCIA * latencia_total) + (W2_PERDA * perda_total) + penalidade

    return fitness_custo, latencia_total, perda_total, penalidade

def amostragem_estocastica(origem, destino, iteracoes=100):
    """Executa a amostragem estocástica (Monte Carlo) para achar a melhor rota."""
    melhor_rota = None
    menor_custo = float('inf')

    for _ in range(iteracoes):
        rota_candidata = gerar_rota_aleatoria(origem, destino)
        custo, lat, loss, pen = calcular_fitness_custo(rota_candidata)

        if custo < menor_custo:
            menor_custo = custo
            melhor_rota = rota_candidata
            melhor_metricas = (lat, loss, pen)

    return melhor_rota, menor_custo, melhor_metricas

if __name__ == "__main__":
    print("=" * 60)
    print(" INICIANDO MOTOR DE DECISÃO SD-WAN (ZERO-TRUST) ")
    print("=" * 60)

    rota, custo, metricas = amostragem_estocastica(origem=0, destino=11, iteracoes=50)
    lat, loss, pen = metricas

    print(f"\n[+] Busca Estocástica Finalizada.")
    print(f"[>] Melhor Rota Encontrada: {rota}")

    reputacoes = [reputacao_seguranca[n] for n in rota]
    print(f"[>] Reputação dos Nós: {reputacoes}")

    print("\n--- Métricas da Rota ---")
    print(f"  * Latência Total     : {lat} ms")
    print(f"  * Perda de Pacotes   : {loss:.1f} %")
    print(f"  * Penalidade Aplicada: {pen}")
    print(f"  * Custo Final (Fit)  : {custo:.2f}")

    if pen == 0:
        print("\n[STATUS] ROTA APROVADA: A conformidade Zero-Trust foi mantida.")
    else:
        print("\n[STATUS] ALERTA DE SEGURANÇA: Rota vulnerável.")
