# -*- coding: utf-8 -*-
"""desafio_ac1_master_sdwan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l91aPwOnqacXGkgWuzGVOoWneLxZqaf1
"""

"""
================================================================================
RELATÓRIO TÉCNICO - MOTOR DE DECISÃO SD-WAN ZERO-TRUST
================================================================================
1. TOPOLOGIA E CONTEXTO:
- Rede configurada com 12 roteadores (Nó 0 como Origem, Nó 11 como Destino).
- Os nós 4 e 8 foram intencionalmente marcados com Índice de Segurança < 50
  (40 e 30, respectivamente), simulando ambientes não confiáveis ou comprometidos.

2. ANÁLISE DE ROTAS:
- A rota fisicamente mais curta e rápida da rede gerada é [0 -> 1 -> 4 -> 11].
  Ela possui uma latência baixíssima (25ms). Contudo, o tráfego passaria pelo
  Nó 4, que possui reputação de segurança violada.
- A presença do Nó 4 aciona a política Zero-Trust, somando a constante de
  penalização P_Seguranca (5000) na função de Fitness (que aqui atua como
  função de Custo a ser minimizada).

3. ROTA SELECIONADA E JUSTIFICATIVA DO DESVIO:
- O algoritmo estocástico ignorou as rotas vulneráveis e convergiu para o
  desvio ideal: [0 -> 3 -> 6 -> 10 -> 11].
- Justificativa: Ao selecionar essa rota, o motor de decisão SD-WAN aceita um
  aumento na latência total (de 25ms para 43ms) para garantir que todos os nós
  do trajeto possuam reputação >= 50. A aplicação estrita de P_Seguranca (5000)
  inviabiliza matematicamente as vias de risco, priorizando a segurança e a
  integridade dos pacotes em detrimento da velocidade bruta.
================================================================================
"""

import numpy as np
import random

# ==================== CONFIGURAÇÕES ====================
# Sementes exigidas para reprodutibilidade
np.random.seed(2026)
random.seed(2026)

# Pesos da Função Fitness (Custo)
W1_LATENCIA = 1.0     # Peso da latência
W2_PERDA = 10.0       # Peso da perda de pacotes
P_SEGURANCA = 5000    # Penalidade Zero-Trust

# ==================== MODELAGEM DOS NÓS ====================
# Índice de Reputação de Segurança (0 a 100). Valores < 50 = Inseguro
reputacao_seguranca = {
    0: 100, 1: 90, 2: 85, 3: 95,
    4: 40,   # Risco! (Abaixo de 50)
    5: 90, 6: 80, 7: 95,
    8: 30,   # Risco! (Abaixo de 50)
    9: 85, 10: 90, 11: 100
}

# Matriz de Adjacência (Lista de adjacência ponderada)
# Estrutura: nó_origem: {nó_destino: {'lat': ms, 'loss': %}}
# Topologia configurada como um DAG (Grafo Direcionado Acíclico) para garantir rotas sem loops infinitos
grafo = {
    0: {1: {'lat': 10, 'loss': 0.1}, 2: {'lat': 12, 'loss': 0.2}, 3: {'lat': 15, 'loss': 0.1}},
    1: {4: {'lat': 5,  'loss': 0.1}, 5: {'lat': 15, 'loss': 0.3}},
    2: {5: {'lat': 10, 'loss': 0.2}, 6: {'lat': 12, 'loss': 0.1}},
    3: {6: {'lat': 10, 'loss': 0.1}, 7: {'lat': 8,  'loss': 0.1}},
    4: {8: {'lat': 10, 'loss': 0.2}, 11: {'lat': 10, 'loss': 0.1}}, # Rota super rápida, mas passa pelo 4
    5: {8: {'lat': 8,  'loss': 0.1}, 9: {'lat': 12, 'loss': 0.2}},
    6: {9: {'lat': 10, 'loss': 0.1}, 10: {'lat': 10, 'loss': 0.1}},
    7: {10: {'lat': 12, 'loss': 0.2}},
    8: {11: {'lat': 5,  'loss': 0.1}},
    9: {11: {'lat': 10, 'loss': 0.1}},
    10: {11: {'lat': 8,  'loss': 0.1}},
    11: {} # Nó destino
}

# ==================== FUNÇÕES DO MOTOR ====================
def gerar_rota_aleatoria(origem, destino):
    """Gera uma rota válida caminhando aleatoriamente pelas adjacências."""
    rota = [origem]
    atual = origem
    while atual != destino:
        vizinhos = list(grafo[atual].keys())
        # Escolhe um vizinho aleatório
        proximo = random.choice(vizinhos)
        rota.append(proximo)
        atual = proximo
    return rota

def calcular_fitness_custo(rota):
    """
    Função Objetivo: Fitness(X) = w1*Latencia + w2*PerdaPacotes + P_Seguranca
    Como queremos a 'melhor' rota, tratamos o Fitness como um CUSTO a ser MINIMIZADO.
    """
    latencia_total = 0.0
    perda_total = 0.0
    penalidade = 0

    # Avaliar arestas
    for i in range(len(rota) - 1):
        u = rota[i]
        v = rota[i+1]
        latencia_total += grafo[u][v]['lat']
        perda_total += grafo[u][v]['loss']

    # Avaliar segurança dos nós (Zero-Trust)
    for no in rota:
        if reputacao_seguranca[no] < 50:
            penalidade = P_SEGURANCA
            break # Basta um nó comprometido para queimar a rota inteira

    fitness_custo = (W1_LATENCIA * latencia_total) + (W2_PERDA * perda_total) + penalidade

    return fitness_custo, latencia_total, perda_total, penalidade

def amostragem_estocastica(origem, destino, iteracoes=100):
    """Executa a amostragem estocástica (Monte Carlo) para achar a melhor rota."""
    melhor_rota = None
    menor_custo = float('inf')

    for _ in range(iteracoes):
        rota_candidata = gerar_rota_aleatoria(origem, destino)
        custo, lat, loss, pen = calcular_fitness_custo(rota_candidata)

        if custo < menor_custo:
            menor_custo = custo
            melhor_rota = rota_candidata
            melhor_metricas = (lat, loss, pen)

    return melhor_rota, menor_custo, melhor_metricas

# ==================== EXECUÇÃO PRINCIPAL ====================
if __name__ == "__main__":
    print("=" * 60)
    print(" INICIANDO MOTOR DE DECISÃO SD-WAN (ZERO-TRUST) ")
    print("=" * 60)

    rota, custo, metricas = amostragem_estocastica(origem=0, destino=11, iteracoes=50)
    lat, loss, pen = metricas

    print(f"\n[+] Busca Estocástica Finalizada.")
    print(f"[>] Melhor Rota Encontrada: {rota}")

    # Mostra reputação dos nós da rota
    reputacoes = [reputacao_seguranca[n] for n in rota]
    print(f"[>] Reputação dos Nós: {reputacoes}")

    print("\n--- Métricas da Rota ---")
    print(f"  * Latência Total     : {lat} ms")
    print(f"  * Perda de Pacotes   : {loss:.1f} %")
    print(f"  * Penalidade Aplicada: {pen}")
    print(f"  * Custo Final (Fit)  : {custo:.2f}")

    if pen == 0:
        print("\n[STATUS] ROTA APROVADA: A conformidade Zero-Trust foi mantida.")
    else:
        print("\n[STATUS] ALERTA DE SEGURANÇA: Rota vulnerável.")